# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: WalletConnectWebExample CI

on: [ push,workflow_dispatch ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    defaults:
      run:
        working-directory: dapps/react-dapp-v2
    runs-on: ubuntu-latest
    environment: 
      name: development
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: |
          dapps/react-dapp-v2/yarn.lock
          ${{ github.workspace }}/dapps/react-dapp-v2/.next/cache
    - name: create env file
      run: |
        touch .env
        echo NEXT_PUBLIC_PROJECT_ID=${{ vars.NEXT_PUBLIC_PROJECT_ID }} >> .env
    - run: yarn install
    - run: yarn build
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: '/dapps/react-dapp-v2/_app'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
